from autogen import AssistantAgent
import asyncio
import os

class TestSuiteagent:

    def create_agent(llm_config):
        system_message="""You are an expert in C# unit testing, specifically using NUnit.
        Your task is to generate comprehensive unit tests for the provided C# code.

        **Instructions:**
        1.  Assume the C# code you are testing is in a project referenced by the test project.
        2.  Generate NUnit tests within a class named 'AutoGeneratedTests' or similar, in a namespace like 'GeneratedModule.AI'.
        3.  Ensure necessary 'using' statements are included (e.g., `using NUnit.Framework;`, `using YourNamespace;`).
        4.  Cover various scenarios, including normal cases, edge cases, and potential error conditions.
        5.  Output **only** the C# code for the test class. Do not include the main application code or any explanatory text outside the code block.
        6.  The output should be a single C# code block inside a markdown block: ```csharp ... ```
        7.  Example structure:
            ```csharp
            using NUnit.Framework;
            using YourNamespace; // Adjust this based on the code being tested

            namespace TestProject
            {
                [TestFixture]
                public class ApplicationManagerTests
                {
                    [Test]
                    public void TestMethod1()
                    {
                        // Arrange
                        // Act
                        // Assert
                    }

                    // ... more tests
                }
            }
            ```
        """
    
        test_agent = AssistantAgent(
            name="TestSuiteAssistant",
            llm_config=llm_config,
            system_message=system_message
        )

        return test_agent
        
